name:  MoveTK-CI-Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
            repository: microsoft/vcpkg
            path: vcpkg-ports
            ref: '2020.07'
      # Checkout repository
      - uses: actions/checkout@v2
        with:
            repository: heremaps/movetk
            path: movetk   
      # Get the ninja generator
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: list dirs
        run:  dir "C:\"
      # Install movetk dependencies
      - name: install dependencies
        run: C:\vcpkg\vcpkg.exe install boost-graph boost-iostreams boost-geometry boost-log gdal gsl cgal geographiclib --overlay-ports="C:\vcpkg-ports" --triplet x64-windows 
      # Build movetk
      - name: build movetk
        run: .\ci.cmd 	 
