name:  MoveTK-CI-Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
            repository: microsoft/vcpkg
            path: vcpkg-202007
            ref: '2020.07'
      # Checkout repository
      - uses: actions/checkout@v2
        with:
            repository: heremaps/movetk
            submodules: recursive
            path: movetk   
      # Get the ninja generator
      - uses: seanmiddleditch/gha-setup-ninja@master
      # Install movetk dependencies
      #- name: install dependencies
      #  run: C:\vcpkg\vcpkg.exe install boost-graph boost-iostreams boost-geometry boost-log gdal gsl cgal geographiclib  cgal --overlay-ports=${{ github.workspace }}\vcpkg-202007\ports --triplet x64-windows 
      # Restore from cache the previously built ports. If "cache miss", then provision vcpkg, install desired ports, finally cache everything for the next run.
      - name: Set vcpkg's response file path used as part of cache's key.
        uses: lukka/set-shell-env@master
        with:
          VCPKGRESPONSEFILE: ${{ github.workspace }}\movetk\src\vcpkg_response_file.txt
      - name: Restore from cache and run vcpkg
        uses: lukka/run-vcpkg@main
        id: runvcpkg
        with:
          # Response file stored in source control, it provides the list of ports and triplet(s).
          vcpkgArguments: '@${{ env.vcpkgResponseFile }} --overlay-ports=${{ github.workspace }}\vcpkg-202007\ports'
          # Location of the vcpkg as submodule of the repository.
          vcpkgDirectory: '${{ github.workspace }}\vcpkg-202007'
          # Since the cache must be invalidated when content of the response file changes, let's
          # compute its hash and append this to the computed cache's key.
          appendedCacheKey: ${{ hashFiles(env.vcpkgResponseFile) }}
      # Build movetk
      - name: build movetk
        run: |
            cd ${{ github.workspace }}\movetk
            dir 
            .\ci.cmd 	 
