name:  MoveTK-CI-Windows

on:
  push:
    branches: [ add-documentation ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    #- name: install dependencies
    #  run: C:\vcpkg\vcpkg.exe install boost gdal cgal geographiclib --triplet x64-windows
    - name: build movetk
      run: .\ci.cmd 	 
