name: MoveTK-create-docker-image

on:
  push:
    branches: [ create-build-artifacts ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - name: Git checkout
          uses: actions/checkout@v2
        - name: Get version
          run: echo "${{ github.ref }}"
        - name: Docker build
          run:  docker build -t movetk -f  ./docker/with_jupyterlab/Dockerfile .
        - name: Login to Github Package
          uses: docker/login-action@v1
          with:
              username: ${{ secrets.DOCKER_USER }}
              password: ${{ secrets.DOCKER_PASSWORD }}
              registry: "docker.io"
        - name: Docker push
          run:  docker push aniketmitra001/movetk:latest
